var geojson = {
    "type": "Feature",
    "properties": { "id": "2100055", "name": "Açailândia", "description": "Açailândia" },
    "geometry": {
        "type": "GeometryCollection",
        "geometries": [{ "type": "Polygon", "coordinates": [-47.50539, -4.94746] }, {
                "type": "Polygon",
                "coordinates": [
                    [
                        [-47.0166128751, -4.4195566281],
                        [-46.9989530262, -4.4268129085],
                        [-46.9826291009, -4.4222529553],
                        [-46.97864515, -4.4255482808],
                        [-46.9656822999, -4.4244889775],
                        [-46.9488214592, -4.4341516073],
                        [-46.9371754345, -4.4322828759],
                        [-46.9325900273, -4.4437904371],
                        [-46.9150261547, -4.4369116168],
                        [-46.9059499962, -4.4284525848],
                        [-46.8932720232, -4.4288854741],
                        [-46.8856431726, -4.4254921604],
                        [-46.8734865245, -4.4305576787],
                        [-46.8433117698, -4.3963242928],
                        [-46.8409240514, -4.3999967814],
                        [-46.8432387661, -4.4028051449],
                        [-46.8425810966, -4.4289888464],
                        [-46.8558900088, -4.4352600173],
                        [-46.8587394702, -4.4410027834],
                        [-46.8582294652, -4.4546855887],
                        [-46.8647739815, -4.4574614766],
                        [-46.8663336778, -4.4665680069],
                        [-46.8759549137, -4.47227507],
                        [-46.8926203171, -4.4832437388],
                        [-46.9023592832, -4.5007754447],
                        [-46.9058075989, -4.5016344955],
                        [-46.9107346876, -4.5179328336],
                        [-46.9092661798, -4.5238006414],
                        [-46.918712238, -4.5347431303],
                        [-46.9143518571, -4.5461068436],
                        [-46.9162898578, -4.5559631574],
                        [-46.9266307773, -4.5667939674],
                        [-46.9274489793, -4.5747602192],
                        [-46.9385828557, -4.5846901225],
                        [-46.9346389261, -4.5934642279],
                        [-46.9381468005, -4.6059071166],
                        [-46.9358229337, -4.6096771635],
                        [-46.9357696879, -4.6098660167],
                        [-46.9416877475, -4.6324858632],
                        [-46.9352893057, -4.6497357567],
                        [-46.934265577, -4.6750331228],
                        [-46.9251641702, -4.6840256633],
                        [-46.9268709322, -4.6907535019],
                        [-46.9342149878, -4.6937164313],
                        [-46.9340648468, -4.7040095535],
                        [-46.9330961833, -4.7187219002],
                        [-46.9386791535, -4.7287651659],
                        [-46.9388026968, -4.7374312297],
                        [-46.9370531351, -4.7504842684],
                        [-46.9261925097, -4.7689415251],
                        [-46.9289213511, -4.7869601549],
                        [-46.9176774832, -4.8079897947],
                        [-46.9211963085, -4.8272183024],
                        [-46.9205261747, -4.8352870948],
                        [-46.9157791486, -4.841276196],
                        [-46.9225278454, -4.8416550133],
                        [-46.9232397004, -4.8477286583],
                        [-46.9268062453, -4.8465253445],
                        [-46.92951772, -4.8501893475],
                        [-46.9186464916, -4.8502010924],
                        [-46.9260066008, -4.8792744904],
                        [-46.923735529, -4.8828632202],
                        [-46.9293094816, -4.8889232471],
                        [-46.928357352, -4.9032744711],
                        [-46.9180614102, -4.9113694115],
                        [-46.9255068844, -4.9115734532],
                        [-46.9281092631, -4.9204001036],
                        [-46.9126830799, -4.9390711739],
                        [-46.9197690385, -4.952875354],
                        [-46.9105849251, -4.9687045399],
                        [-46.9107336585, -4.9856398931],
                        [-46.9063701067, -4.9968296018],
                        [-46.9146970984, -5.0080882352],
                        [-46.947921692, -5.03204926],
                        [-46.9950885367, -5.048717467],
                        [-47.0001389865, -5.0475318723],
                        [-47.0250140826, -5.0490714029],
                        [-47.0417314336, -5.0601776126],
                        [-47.0604641089, -5.0555192686],
                        [-47.0790467935, -5.0568620541],
                        [-47.0997368628, -5.069324932],
                        [-47.0979013596, -5.0782138482],
                        [-47.101724774, -5.0837519412],
                        [-47.1088177738, -5.089185669],
                        [-47.1117597128, -5.0862350996],
                        [-47.1169504182, -5.0871341614],
                        [-47.112929959, -5.0999364079],
                        [-47.1194138437, -5.1004372299],
                        [-47.1236677541, -5.1051963411],
                        [-47.1281340794, -5.122619899],
                        [-47.1371620046, -5.1332602786],
                        [-47.1351307007, -5.1429988777],
                        [-47.2146152696, -5.1679289302],
                        [-47.2296185079, -5.1512248057],
                        [-47.2491558173, -5.1022840881],
                        [-47.2584369737, -5.0919903515],
                        [-47.2598639262, -5.0853329292],
                        [-47.2632109093, -5.085411686],
                        [-47.2686378675, -5.0877160697],
                        [-47.2707211124, -5.0814146578],
                        [-47.2804159866, -5.0805818225],
                        [-47.2898623781, -5.0857775992],
                        [-47.2909181867, -5.078777218],
                        [-47.3008735517, -5.0815170708],
                        [-47.3121580287, -5.0758406717],
                        [-47.3139712462, -5.0639244742],
                        [-47.3208626513, -5.0583783997],
                        [-47.3153605965, -5.0435550313],
                        [-47.3206065869, -5.0458326634],
                        [-47.3303051092, -5.0432593082],
                        [-47.3413172286, -5.0359489481],
                        [-47.3444220741, -5.0281842408],
                        [-47.3500643014, -5.0260963006],
                        [-47.3655079556, -5.0284642346],
                        [-47.4016518754, -5.0343034982],
                        [-47.4763067164, -5.0463606793],
                        [-47.4757229534, -5.062723238],
                        [-47.4812807012, -5.0727049454],
                        [-47.4938384615, -5.0768112893],
                        [-47.5016748472, -5.0645927949],
                        [-47.5115249291, -5.0616169279],
                        [-47.5374933577, -5.0816106794],
                        [-47.5419340198, -5.0886597586],
                        [-47.5539061742, -5.0948331833],
                        [-47.554022109, -5.0947840126],
                        [-47.5541425707, -5.0947330895],
                        [-47.678821602, -5.0416795298],
                        [-47.6847522433, -5.0360693525],
                        [-47.6968059478, -5.0292477493],
                        [-47.7128650578, -5.0079678072],
                        [-47.7168083594, -4.9861073089],
                        [-47.7511139265, -4.9634738373],
                        [-47.7756707317, -4.9565139243],
                        [-47.7780606593, -4.9453198431],
                        [-47.7922763102, -4.9348308264],
                        [-47.8011717931, -4.9335189649],
                        [-47.8033075238, -4.9275454835],
                        [-47.8061963079, -4.9290152753],
                        [-47.804190268, -4.9219154963],
                        [-47.8094737975, -4.9181414099],
                        [-47.8131728878, -4.9208081341],
                        [-47.820671823, -4.9034561471],
                        [-47.8282190536, -4.9000629572],
                        [-47.8298535025, -4.888318257],
                        [-47.8370554791, -4.8776007433],
                        [-47.8494705416, -4.8696843682],
                        [-47.8548901523, -4.8706516549],
                        [-47.8562090669, -4.8612537998],
                        [-47.8605263437, -4.854342261],
                        [-47.8665007414, -4.8549663533],
                        [-47.8695563158, -4.8519609772],
                        [-47.8948056643, -4.8364068456],
                        [-47.9161340528, -4.8303836853],
                        [-47.9315250561, -4.8161068751],
                        [-47.9394473894, -4.8151069301],
                        [-47.9675178605, -4.7908592762],
                        [-47.9771451063, -4.7881457284],
                        [-47.979637241, -4.784392866],
                        [-47.9963061564, -4.7803822841],
                        [-48.0059696087, -4.7853646382],
                        [-48.0155319762, -4.7783738015],
                        [-48.0249489835, -4.7779158228],
                        [-47.8157262982, -4.6143496619],
                        [-47.8047016185, -4.5969907466],
                        [-47.7921426019, -4.5860321569],
                        [-47.7858650543, -4.5856865826],
                        [-47.770443511, -4.5929358263],
                        [-47.753614233, -4.5904448759],
                        [-47.7503646298, -4.6001122268],
                        [-47.7418301581, -4.5982406419],
                        [-47.724386808, -4.6060392766],
                        [-47.7148625329, -4.6026628606],
                        [-47.711336684, -4.6028925827],
                        [-47.7114995489, -4.6058865429],
                        [-47.7011394019, -4.6044029812],
                        [-47.679549478, -4.6082557462],
                        [-47.6811289307, -4.6232216043],
                        [-47.6857929027, -4.6280917434],
                        [-47.6822840366, -4.6388363619],
                        [-47.6869201692, -4.6410654691],
                        [-47.6883817075, -4.6461535862],
                        [-47.6927785832, -4.6503509946],
                        [-47.6880374436, -4.6845483098],
                        [-47.685518618, -4.6901023778],
                        [-47.687969142, -4.6921280173],
                        [-47.6988138178, -4.7005699475],
                        [-47.6990404546, -4.7113076274],
                        [-47.7009722852, -4.7168695042],
                        [-47.6935915936, -4.724048935],
                        [-47.690036455, -4.7229623881],
                        [-47.6877071044, -4.7210932074],
                        [-47.6805921462, -4.7122890689],
                        [-47.6741621596, -4.7119442006],
                        [-47.6554646243, -4.7151454682],
                        [-47.6456485718, -4.7268901053],
                        [-47.6151496772, -4.7016393802],
                        [-47.604129476, -4.7055904605],
                        [-47.592642909, -4.7052455236],
                        [-47.5925183905, -4.705259663],
                        [-47.513130432, -4.703512823],
                        [-47.4953081647, -4.6995943891],
                        [-47.4952206356, -4.6520268323],
                        [-47.4867967431, -4.647862898],
                        [-47.4703018084, -4.6491677141],
                        [-47.4437122929, -4.6348182968],
                        [-47.4256655882, -4.636513272],
                        [-47.3929174831, -4.6517569769],
                        [-47.3876534236, -4.65084456],
                        [-47.3894686641, -4.6561322046],
                        [-47.3864100567, -4.65800817],
                        [-47.3668487422, -4.6689347357],
                        [-47.3345043144, -4.6762017227],
                        [-47.338662443, -4.6899244459],
                        [-47.3058876141, -4.6982953607],
                        [-47.2859722107, -4.6957429444],
                        [-47.2751337973, -4.6852879493],
                        [-47.2354405377, -4.6466535736],
                        [-47.230143685, -4.6361027387],
                        [-47.226376839, -4.6286012135],
                        [-47.2262621612, -4.5924410889],
                        [-47.2351396246, -4.549927618],
                        [-47.2479272875, -4.5309162334],
                        [-47.2530302232, -4.5280410832],
                        [-47.2479756523, -4.5223343442],
                        [-47.2540602939, -4.5089161611],
                        [-47.2535343396, -4.4999283145],
                        [-47.2481352347, -4.4920955606],
                        [-47.2494919687, -4.4690499074],
                        [-47.2414216855, -4.4365475222],
                        [-47.2435930242, -4.4316268145],
                        [-47.2215762701, -4.4249479228],
                        [-47.2098812753, -4.4062798622],
                        [-47.1873330825, -4.3882999377],
                        [-47.1380961936, -4.3182605692],
                        [-47.1256399855, -4.2836096696],
                        [-47.1005579035, -4.2647317981],
                        [-47.0951125843, -4.246900854],
                        [-47.0897061343, -4.2412342184],
                        [-47.0777161184, -4.2362390538],
                        [-47.0723193464, -4.2362529777],
                        [-47.0688394066, -4.2630771624],
                        [-47.0724205187, -4.2736402419],
                        [-47.0829211776, -4.2839748028],
                        [-47.0820636453, -4.2941319987],
                        [-47.087835998, -4.3029304718],
                        [-47.0875130878, -4.3081411497],
                        [-47.0731690399, -4.3234048754],
                        [-47.0697479592, -4.3396020394],
                        [-47.0626701937, -4.3443333145],
                        [-47.0593659613, -4.3663062896],
                        [-47.0426116627, -4.3756707456],
                        [-47.038903782, -4.3830893881],
                        [-47.031444262, -4.3877772874],
                        [-47.0282783566, -4.3987708024],
                        [-47.0204119662, -4.4057821573],
                        [-47.0166128751, -4.4195566281]
                    ]
                ]
            },


        ]


    }
}

function loadDadosMunicipios(){

    fetch("/js/geojson/area-municipios-ma-br.geojson")
    .then(function(response) {
        return response.json();
    })
    .then(function(data) {
        L.geoJSON(data).addTo(map);
        for(var mun of data.features) {
            //console.log(mun.properties.name)
             ;
        }

    fetch("/js/geojson/pins-municipios-ma-br.geojson")
    .then(function(response) {
        return response.json();
    })
    .then(function(pins) {
        L.geoJSON(pins).addTo(map);
        
    });
//  add geojson  
geoLayer = L.geoJson(data).addTo(map),

// color scale from http://colorbrewer2.org
colors = ['#db4a52'];

// set base styles
geoLayer.setStyle({
    width: 735,
    height: 860,
    fillOpacity: 1,
    color: 'white',
    weight: 1,

});

updateColors();

// sets color of each layer randomly
function updateColors() {

    geoLayer.eachLayer(function(layer) {
        var col = colors[~~(Math.random() * colors.length)];
        layer.setStyle({ fillColor: col });
    });

    setTimeout(updateColors, 1500);
}

    });
    
}

loadDadosMunicipios()

// var view = 'calor';
// var locateUser = 0;
// var casosTotal = 0, mortesTotal = 0;
// var casosTotalMA = 0, mortesTotalMA = 0;
// var casosTotalBR = 0, mortesTotalBR = 0;
// var data_atualizacao = '00/00/0000';

// create map


var map = new L.Map('map', {
    center: new L.LatLng(-5.00891349418116, -45.43778011911654),
    zoom: 6.5,
    zoomControl: false,
    dragging: false,
    scrollWheelZoom: false,
    doubleClickZoom: false,
    boxZoom: false,
    tap: false
});

//SET LOCATE ---------------------------------------------------
// function onLocationFound(e) {
//     // var radius = e.accuracy;
//      var location = e.latlng
//      if(locateUser == 0 ){ L.marker(location, {icon: iconUser}).addTo(map); locateUser = 1; } 
//      else{ false } 
//      //L.circle(location, radius).addTo(map);
//   }

//   function onLocationError(e) {
//      //alert(e.message);
//      //alert('Seu local n\u00e3o pode ser encontrado!\nTalvez seu sinal esteja fraco, tente novamente!');

//     Swal.fire({
//     title: 'ERRO!',
//     text: 'Seu local n\u00e3o pode ser encontrado!\nTalvez seu sinal esteja fraco, tente novamente!',
//     icon: 'error',
//     confirmButtonText: 'FECHAR'
//     })
//   }

//   function getLocationLeaflet() {
//      map.on('locationfound', onLocationFound);
//      map.on('locationerror', onLocationError);

//      map.locate({setView: true, maxZoom: 16});
//   }

//MAPA DE CALOR ---------------------------------------------------------------------------

// var mapasgroup0 = null;
// fetch("/js/geojson/area-municipios-ma-br.geojson").then(response => response.json().then(
//     // function(data){  

//     // //     if(view == 'calor'){
//     // //     //Total de casos
//     // //     // casosTotal = data[1][0][5]; mortesTotal = data[1][0][6];
//     // //     // document.getElementById('casosTotal').innerHTML = data[1][0][5];

//     // //     // //Total de óbitos
//     // //     // document.getElementById('mortesTotal').innerHTML = data[1][0][6];

//     // //     // //Ultimo Registro
//     // //     // document.getElementById('data_atualizacao').innerHTML = data[1][0][7];
        
//     // // }

//     //     //Heat
//     //     // var addressPoints = data[0];
//     //     // addressPoints = addressPoints.map(function (p) { return [p[0], p[1]]; });
//     //     // var heat = L.heatLayer(addressPoints,{
//     //     //     //minOpacity: 0.7,
//     //     //     maxZoom: 6, //Em relação ao mapa  6
//     //     //     radius: 21, //25
//     //     //     max: 1.0, //1.0
//     //     //     blur: 17, // 15
//     //     //     //gradient: {0.4: 'blue', 0.65: 'lime', 1: 'red'}
//     //     // })
//     //     // //map.hasLayer(heat) //se layer existe

//     //     //In zoom, hidden heatmap
//     //     // map.on('movestart', function(ev) { 

//     //     //     if(map.hasLayer(mapasgroup0) == true)
//     //     //     {
//     //     //         //console.log(map.hasLayer(heat)+'----------------------------------------');
//     //     //         heat.setOptions({ max: 0, blur: 0 });
//     //     //         heat.redraw(); 
//     //     //     }

//     //     // });
//     //     // //Map pause block heatmap
//     //     // map.on('moveend', function(ev) {
//     //     //     if(map.hasLayer(mapasgroup0) == true)
//     //     //     {
//     //     //         heat.setOptions({ max: 1.0, blur: 17 });
//     //     //         heat.redraw(); 
//     //     //     }
//     //     // });
        

//     //     // mapasgroup0 = new L.LayerGroup([heat]);
    
//     //     //Pin Heat
//     //     // var pinHeat = [];

//     //     // var iconTransparent = L.icon({
//     //     // iconUrl: 'js/leaflet/images/transparent.png',
//     //     // //iconRetinaUrl: 'my-icon@2x.png',
//     //     // //iconSize: [16, 16],
//     //     // //iconAnchor: [22, 94],
//     //     // //popupAnchor: [-3, -76],
//     //     // //shadowUrl: 'my-icon-shadow.png',
//     //     // //shadowRetinaUrl: 'my-icon-shadow@2x.png',
//     //     // //shadowSize: [68, 95],
//     //     // //shadowAnchor: [22, 94]
//     //     // });

//     //     //var iconTransparent = L.Icon.extend({iconUrl: 'js/leaflet/images/transparent.png'});
//     //     // for(let i = 0; i < data[1].length; i++)
//     //     // {
//     //     //     //console.log(data[1][i][0]);
//     //     //     pinHeat[i] = L.marker([data[1][i][1],data[1][i][2]], {icon: iconTransparent}).
//     //     //     bindPopup('<h3 class="popUpMap">'+data[1][i][0]+'</h3>'+
//     //     //     '<ul class="popUpMapUl">'+
//     //     //     '<li class="popUpMapUlLiVirus"><b>Casos: </b>'+data[1][i][3]+'</li>'+
//     //     //     '<li class="popUpMapUlLiMorte"><b>&Oacute;bitos: </b>'+data[1][i][4]+'</li>'+
//     //     //     '</ul>');
//     //     //     mapasgroup0.addLayer(pinHeat[i]);
//     //     // }

//     //     //mapasgroup0.addTo(map);

//     // }
// )).catch(function(err){ console.log('ERRO: Fetch Error MAP HEAT', err); });
  /*FUNÇÃO DE POLIGONO*/

//   var mouseover = true;
//   function poligono(poligono, layer)
// 	{		
// 		layer.setStyle({
// 			fillColor: '', 
// 			weight: 2,
// 			opacity: 1,
// 			color: 'white',
// 			dashArray: '3',
// 			fillOpacity: 0.7
// 		});
// 		layer.bindPopup(poligono.properties.description).addEventListener("mouseover", function (e){ alert('ok');})
// 		layer.bindPopup(poligono.properties.description);

// 		casosTotalMA = poligono.properties.casosTotalMA; 
// 		mortesTotalMA = poligono.properties.mortesTotalMA; 
// 		data_atualizacao = poligono.properties.data_atualizacao; 

// 		if(view == 'areaMA'){
// 		document.getElementById('casosTotal').innerHTML = casosTotalMA;
// 		document.getElementById('mortesTotal').innerHTML = mortesTotalMA;
// 		document.getElementById('data_atualizacao').innerHTML = data_atualizacao;
// 		}
// 	}


    // //Pop-Up pins
	// function popUp(f,l){
	// 	var out = [];

	// 	if (f.properties){
		
	// 		for(key in f.properties){

	// 			if(key == 'description'){out.push(f.properties[key]);}
	// 			//if(key == 'id'){out.push("<span id='idRegMap"+f.properties.id+"'>id</span>: "+"<b>"+f.properties.id+"</b>");}
	// 			//else{out.push(key+": "+"<b>"+f.properties[key]+"</b>");}

	// 			if(key == 'casosTotalBR'){ casosTotalBR = f.properties[key]; }
	// 			if(key == 'mortesTotalBR'){ mortesTotalBR = f.properties[key]; }
	// 			if(key == 'data_atualizacao'){ data_atualizacao = f.properties[key]; }

	// 			if(view == 'pinBR'){
	// 				document.getElementById('casosTotal').innerHTML = casosTotalBR;
	// 				document.getElementById('mortesTotal').innerHTML = mortesTotalBR;
	// 				document.getElementById('data_atualizacao').innerHTML = data_atualizacao;
	// 			}

	// 		}
	// 		l.bindPopup(out.join("<br />"));
			
	// 		l.on('click', function(){ 
	// 			//console.log(l._popup.getContent()); //text pop-up
	// 			let elementId =  l._popup.getElement(); //text|html	pop-up		
	// 			//let docmentSpan = (elementId.getElementsByTagName('span')[0].id);
	// 			//console.log(docmentSpan);
	// 		});
	// 	}
	// }

    // //Dados por geojson
	// var myStyle = {
    //     //"color": "#22b573",
    //     "weight": 1,
    //     "opacity": 1,
	// 	//"dashArray": 5
    // };
	//var geojsonLayer = new L.GeoJSON.AJAX(["/js/geojson/area-municipios-ma-br.geojson","/js/geojson/pins-municipios-ma-br.geojson"],{onEachFeature:popUp})/*.addTo(map)*/;
	//var geojsonLayer1 = new L.GeoJSON.AJAX(["js/geojson/area-estados-br.geojson","js/geojson/pins-estados-br.geojson"],{style:myStyle, onEachFeature:popUp})/*.addTo(map)*/;
	
    //LAYER GROUP ----------------------------------------------------------------------------
	//var mapasgroup1 = new L.LayerGroup([geojsonLayer]);
	//var mapasgroup2 = new L.LayerGroup([geojsonLayer1]);
/*
/



/*FUNCIONA MAIS OU MENOS*/
// gpsMarker = new L.geoJson(data, {
//     onEachFeature: function(FeatureCollection, layer) {

//         if (FeatureCollection.properties && FeatureCollection.properties.popupContent) {
//             layer.bindPopup(FeatureCollection.properties.popupContent, { closeButton: false, offset: L.point(0, -20) });
//             layer.on('   seover', function() { layer.openPopup(); });
//             layer.on('mouseout', function() { layer.closePopup(); });
//         }
//     },

// });

// map.addLayer(gpsMarker);
// map.fitBounds(gpsMarker.getBounds(), { padding: [0, 0] });

// var layerPopup;
// featureLayer.on('mouseover', function(e){
//     var coordinates = e.layer.feature.geometry.coordinates;
//     var swapped_coordinates = [coordinates[1], coordinates[0]];  //Swap Lat and Lng
//     if (map) {
//        layerPopup = L.popup()
//            .setLatLng(swapped_coordinates)
//            .setContent('Popup for feature #'+e.layer.feature.properties.id)
//             .openOn(map);
//     }
// });
// featureLayer.on('mouseout', function (e) {
//     if (layerPopup && map) {
//         map.closePopup(layerPopup);
//         layerPopup = null;
//     }
// });*/